version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - red-interna

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_USER=sa
      - DB_PASSWORD=TuPasswordSegura123
      - DB_HOST=db
      - DB_NAME=PruebaTecnica
    depends_on:
      - db
    networks:
      - red-interna

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1533:1433"
    environment:
      - SA_PASSWORD=TuPasswordSegura123
      - ACCEPT_EULA=Y
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - red-interna

networks:
  red-interna:

volumes:
  mssql_data:
